const mongoose = require("mongoose");

const articlesSchema = new mongoose.Schema({
  userRef: {
    type: mongoose.Schema.ObjectId,
    ref: "users",
    required: Boolean,
  },
  userName: {
    type: String,
    required: true,
  },
  productImage: {
    type: String,
  },
  techPackImage: {
    type: String,
  },
  styleNumber: {
    type: Number,
  },
  itemNumber: {
    type: Number,
  },
  fabricContent: {
    type: String,
  },
  description: {
    type: String,
  },
  modeType: {
    type: String,
  },
  colorCount: {
    type: Number,
  },
  designFile: [],
  deliveryDate: {
    type: Date,
    default: new Date(),
  },
  isFitSample: {
    type: Boolean,
  },
  isArticleDelivered: {
    type: Boolean,
    default: false,
  },
  isSTDFileReceived: {
    type: Boolean,
    default: false,
  },
  createdAt: {
    type: Date,
    default: new Date(),
  },
  updatedAt: {
    type: Date,
  },
  selectedPiecesQuantity: {
    type: String,
  },
  onePieceFabricQuality: String,
  onePieceFabricConstruction: String,
  onePieceFabricWeight: String,
  onePieceColorComboName: String,
  onePieceType: String,
  onePieceStandard: String,
  onePieceSTDReceived: String,
  onePieceSTDReceivedDate: String,
  onePieceSTDDetail: String,
  onePieceSTDIfCADFile: String,
  onePieceFirstSubmitDate: String,
  onePieceFirstSubmitCommentReceivedDate: String,
  onePieceFirstSubmitStatus: String,
  onePieceFirstSubmitComment: String,
  onePieceSecondSubmitDate: String,
  onePieceSecondSubmitCommentReceivedDate: String,
  onePieceSecondSubmitStatus: String,
  onePieceSecondSubmitComment: String,
  TwoPJArticleIdenticalTopBottomPieces: Boolean,
  TwoPJArticleFabricQuality: String,
  TwoPJArticleFabricConstruction: String,
  TwoPJArticleFabricWeight: String,
  TwoPJArticleColorComboName: String,
  TwoPJArticleType: String,
  TwoPJArticleStandard: String,
  TwoPJArticleSTDReceived: String,
  TwoPJArticleSTDReceivedDate: String,
  TwoPJArticleSTDDetail: String,
  TwoPJArticleSTDIfCADFile: String,
  TwoPJArticleFirstSubmitDate: String,
  TwoPJArticleFirstSubmitCommentsReceivedDate: String,
  TwoPJArticleFirstSubmitStatus: String,
  TwoPJArticleFirstSubmitComment: String,
  TwoPJArticleSecondSubmitDate: String,
  TwoPJArticleSecondSubmitCommentReceivedDate: String,
  TwoPJArticleSecondSubmitStatus: String,
  TwoPJArticleSecondSubmitComment: String,
  TwoPJArticleTopFabricQuality: String,
  TwoPJArticleTopFabricConstruction: String,
  TwoPJArticleTopFabricWeight: String,
  TwoPJArticleTopFabricColorComboName: String,
  TwoPJArticleTopFabricType: String,
  TwoPJArticleTopFabricStandard: String,
  TwoPJArticleTopFabricSTDReceived: String,
  TwoPJArticleTopFabricSTDReceivedDate: String,
  TwoPJArticleTopFabricSTDDetail: String,
  TwoPJArticleTopFabricSTDIfCADFile: String,
  TwoPJArticleTopFabricFirstSubmitDate: String,
  TwoPJArticleTopFabricFirstSubmitCommentsReceivedDate: String,
  TwoPJArticleTopFabricFirstSubmitStatus: String,
  TwoPJArticleTopFabricFirstSubmitComment: String,
  TwoPJArticleTopFabricSecondSubmitDate: String,
  TwoPJArticleTopFabricSecondSubmitCommentReceivedDate: String,
  TwoPJArticleTopFabricSecondSubmitStatus: String,
  TwoPJArticleTopFabricSecondSubmitComment: String,
  TwoPJArticleBottomFabricQuality: String,
  TwoPJArticleBottomFabricConstruction: String,
  TwoPJArticleBottomFabricWeight: String,
  TwoPJArticleBottomFabricColorComboName: String,
  TwoPJArticleBottomFabricType: String,
  TwoPJArticleBottomFabricStandard: String,
  TwoPJArticleBottomFabricSTDReceived: String,
  TwoPJArticleBottomFabricSTDReceivedDate: String,
  TwoPJArticleBottomFabricSTDDetail: String,
  TwoPJArticleBottomFabricSTDIfCADFile: String,
  TwoPJArticleBottomFabricFirstSubmitDate: String,
  TwoPJArticleBottomFabricFirstSubmitCommentsReceivedDate: String,
  TwoPJArticleBottomFabricFirstSubmitStatus: String,
  TwoPJArticleBottomFabricFirstSubmitComment: String,
  TwoPJArticleBottomFabricSecondSubmitDate: String,
  TwoPJArticleBottomFabricSecondSubmitCommentReceivedDate: String,
  TwoPJArticleBottomFabricSecondSubmitStatus: String,
  TwoPJArticleBottomFabricSecondSubmitComment: String,
  TwoArticleComponentArticleNoOneIdenticalTopBottomPieces: Boolean,
  TwoArticleComponentArticleNoOneFabricQuality: String,
  TwoArticleComponentArticleNoOneFabricConstruction: String,
  TwoArticleComponentArticleNoOneWeight: String,
  TwoArticleComponentArticleNoOneColorComboName: String,
  TwoArticleComponentArticleNoOneType: String,
  TwoArticleComponentArticleNoOneStandard: String,
  TwoArticleComponentArticleNoOneSTDReceived: String,
  TwoArticleComponentArticleNoOneSTDReceivedDate: String,
  TwoArticleComponentArticleNoOneSTDDetail: String,
  TwoArticleComponentArticleNoOneSTDIfCADFile: String,
  TwoArticleComponentArticleNoOneFirstSubmitDate: String,
  TwoArticleComponentArticleNoOneFirstSubmitCommentReceivedDate: String,
  TwoArticleComponentArticleNoOneFirstSubmitStatus: String,
  TwoArticleComponentArticleNoOneFirstSubmitComment: String,
  TwoArticleComponentArticleNoOneSecondSubmitDate: String,
  TwoArticleComponentArticleNoOneSecondSubmitCommentReceivedDate: String,
  TwoArticleComponentArticleNoOneSecondSubmitStatus: String,
  TwoArticleComponentArticleNoOneSecondSubmitComment: String,
  TwoArticleComponentArticleNoOneTopFabricQuality: String,
  TwoArticleComponentArticleNoOneTopFabricConstruction: String,
  TwoArticleComponentArticleNoOneTopFabricWeight: String,
  TwoArticleComponentArticleNoOneTopFabricColorComboName: String,
  TwoArticleComponentArticleNoOneTopFabricType: String,
  TwoArticleComponentArticleNoOneTopFabricStandard: String,
  TwoArticleComponentArticleNoOneTopFabricSTDReceived: String,
  TwoArticleComponentArticleNoOneTopFabricSTDReceivedDate: String,
  TwoArticleComponentArticleNoOneTopFabricSTDDetail: String,
  TwoArticleComponentArticleNoOneTopFabricSTDIfCADFile: String,
  TwoArticleComponentArticleNoOneTopFabricFirstSubmitDate: String,
  TwoArticleComponentArticleNoOneTopFabricFirstSubmitCommentReceivedDate:
    String,
  TwoArticleComponentArticleNoOneTopFabricFirstSubmitStatus: String,
  TwoArticleComponentArticleNoOneTopFabricFirstSubmitComment: String,
  TwoArticleComponentArticleNoOneTopFabricSecondSubmitDate: String,
  TwoArticleComponentArticleNoOneTopFabricSecondSubmitCommentReceivedDate:
    String,
  TwoArticleComponentArticleNoOneTopFabricSecondSubmitStatus: String,
  TwoArticleComponentArticleNoOneTopFabricSecondSubmitComment: String,
  TwoArticleComponentArticleNoOneBottomFabricQuality: String,
  TwoArticleComponentArticleNoOneBottomFabricConstruction: String,
  TwoArticleComponentArticleNoOneBottomFabricWeight: String,
  TwoArticleComponentArticleNoOneBottomFabricColorComboName: String,
  TwoArticleComponentArticleNoOneBottomFabricType: String,
  TwoArticleComponentArticleNoOneBottomFabricStandard: String,
  TwoArticleComponentArticleNoOneBottomFabricSTDReceived: String,
  TwoArticleComponentArticleNoOneBottomFabricSTDReceivedDate: String,
  TwoArticleComponentArticleNoOneBottomFabricSTDDetail: String,
  TwoArticleComponentArticleNoOneBottomFabricSTDIfCADFile: String,
  TwoArticleComponentArticleNoOneBottomFabricFirstSubmitDate: String,
  TwoArticleComponentArticleNoOneBottomFabricFirstSubmitCommentReceivedDate:
    String,
  TwoArticleComponentArticleNoOneBottomFabricFirstSubmitStatus: String,
  TwoArticleComponentArticleNoOneBottomFabricFirstSubmitComment: String,
  TwoArticleComponentArticleNoOneBottomFabricSecondSubmitDate: String,
  TwoArticleComponentArticleNoOneBottomFabricSecondSubmitCommentReceivedDate:
    String,
  TwoArticleComponentArticleNoOneBottomFabricSecondSubmitStatus: String,
  TwoArticleComponentArticleNoOneBottomFabricSecondSubmitComment: String,
  TwoArticleComponentArticleNoTwoIdenticalTopBottomPieces: Boolean,
  TwoArticleComponentArticleNoTwoFabricQuality: String,
  TwoArticleComponentArticleNoTwoFabricConstruction: String,
  TwoArticleComponentArticleNoTwoWeight: String,
  TwoArticleComponentArticleNoTwoColorComboName: String,
  TwoArticleComponentArticleNoTwoType: String,
  TwoArticleComponentArticleNoTwoStandard: String,
  TwoArticleComponentArticleNoTwoSTDReceived: String,
  TwoArticleComponentArticleNoTwoSTDReceivedDate: String,
  TwoArticleComponentArticleNoTwoSTDDetail: String,
  TwoArticleComponentArticleNoTwoSTDIfCADFile: String,
  TwoArticleComponentArticleNoTwoFirstSubmitDate: String,
  TwoArticleComponentArticleNoTwoFirstSubmitCommentReceivedDate: String,
  TwoArticleComponentArticleNoTwoFirstSubmitStatus: String,
  TwoArticleComponentArticleNoTwoFirstSubmitComment: String,
  TwoArticleComponentArticleNoTwoSecondSubmitDate: String,
  TwoArticleComponentArticleNoTwoSecondSubmitCommentReceivedDate: String,
  TwoArticleComponentArticleNoTwoSecondSubmitStatus: String,
  TwoArticleComponentArticleNoTwoSecondSubmitComment: String,
  TwoArticleComponentArticleNoTwoTopFabricQuality: String,
  TwoArticleComponentArticleNoTwoTopFabricConstruction: String,
  TwoArticleComponentArticleNoTwoTopFabricWeight: String,
  TwoArticleComponentArticleNoTwoTopFabricColorComboName: String,
  TwoArticleComponentArticleNoTwoTopFabricType: String,
  TwoArticleComponentArticleNoTwoTopFabricStandard: String,
  TwoArticleComponentArticleNoTwoTopFabricSTDReceived: String,
  TwoArticleComponentArticleNoTwoTopFabricSTDReceivedDate: String,
  TwoArticleComponentArticleNoTwoTopFabricSTDDetail: String,
  TwoArticleComponentArticleNoTwoTopFabricSTDIfCADFile: String,
  TwoArticleComponentArticleNoTwoTopFabricFirstSubmitDate: String,
  TwoArticleComponentArticleNoTwoTopFabricFirstSubmitCommentReceivedDate:
    String,
  TwoArticleComponentArticleNoTwoTopFabricFirstSubmitStatus: String,
  TwoArticleComponentArticleNoTwoTopFabricFirstSubmitComment: String,
  TwoArticleComponentArticleNoTwoTopFabricSecondSubmitDate: String,
  TwoArticleComponentArticleNoTwoTopFabricSecondSubmitCommentReceivedDate:
    String,
  TwoArticleComponentArticleNoTwoTopFabricSecondSubmitStatus: String,
  TwoArticleComponentArticleNoTwoTopFabricSecondSubmitComment: String,
  TwoArticleComponentArticleNoTwoBottomFabricQuality: String,
  TwoArticleComponentArticleNoTwoBottomFabricConstruction: String,
  TwoArticleComponentArticleNoTwoBottomFabricWeight: String,
  TwoArticleComponentArticleNoTwoBottomFabricColorComboName: String,
  TwoArticleComponentArticleNoTwoBottomFabricType: String,
  TwoArticleComponentArticleNoTwoBottomFabricStandard: String,
  TwoArticleComponentArticleNoTwoBottomFabricSTDReceived: String,
  TwoArticleComponentArticleNoTwoBottomFabricSTDReceivedDate: String,
  TwoArticleComponentArticleNoTwoBottomFabricSTDDetail: String,
  TwoArticleComponentArticleNoTwoBottomFabricSTDIfCADFile: String,
  TwoArticleComponentArticleNoTwoBottomFabricFirstSubmitDate: String,
  TwoArticleComponentArticleNoTwoBottomFabricFirstSubmitCommentReceivedDate:
    String,
  TwoArticleComponentArticleNoTwoBottomFabricFirstSubmitStatus: String,
  TwoArticleComponentArticleNoTwoBottomFabricFirstSubmitComment: String,
  TwoArticleComponentArticleNoTwoBottomFabricSecondSubmitDate: String,
  TwoArticleComponentArticleNoTwoBottomFabricSecondSubmitCommentReceivedDate:
    String,
  TwoArticleComponentArticleNoTwoBottomFabricSecondSubmitStatus: String,
  TwoArticleComponentArticleNoTwoBottomFabricSecondSubmitComment: String,
  FiveArticleComponentArticleNoOneIdenticalTopBottomPieces: Boolean,
  FiveArticleComponentArticleNoOneFabricQuality: String,
  FiveArticleComponentArticleNoOneFabricConstruction: String,
  FiveArticleComponentArticleNoOneWeight: String,
  FiveArticleComponentArticleNoOneColorComboName: String,
  FiveArticleComponentArticleNoOneType: String,
  FiveArticleComponentArticleNoOneStandard: String,
  FiveArticleComponentArticleNoOneSTDReceived: String,
  FiveArticleComponentArticleNoOneSTDReceivedDate: String,
  FiveArticleComponentArticleNoOneSTDDetail: String,
  FiveArticleComponentArticleNoOneSTDIfCADFile: String,
  FiveArticleComponentArticleNoOneFirstSubmitDate: String,
  FiveArticleComponentArticleNoOneFirstSubmitCommentReceivedDate: String,
  FiveArticleComponentArticleNoOneFirstSubmitStatus: String,
  FiveArticleComponentArticleNoOneFirstSubmitComment: String,
  FiveArticleComponentArticleNoOneSecondSubmitDate: String,
  FiveArticleComponentArticleNoOneSecondSubmitCommentReceivedDate: String,
  FiveArticleComponentArticleNoOneSecondSubmitStatus: String,
  FiveArticleComponentArticleNoOneSecondSubmitComment: String,
  FiveArticleComponentArticleNoOneTopFabricQuality: String,
  FiveArticleComponentArticleNoOneTopFabricConstruction: String,
  FiveArticleComponentArticleNoOneTopFabricWeight: String,
  FiveArticleComponentArticleNoOneTopFabricColorComboName: String,
  FiveArticleComponentArticleNoOneTopFabricType: String,
  FiveArticleComponentArticleNoOneTopFabricStandard: String,
  FiveArticleComponentArticleNoOneTopFabricSTDReceived: String,
  FiveArticleComponentArticleNoOneTopFabricSTDReceivedDate: String,
  FiveArticleComponentArticleNoOneTopFabricSTDDetail: String,
  FiveArticleComponentArticleNoOneTopFabricSTDIfCADFile: String,
  FiveArticleComponentArticleNoOneTopFabricFirstSubmitDate: String,
  FiveArticleComponentArticleNoOneTopFabricFirstSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoOneTopFabricFirstSubmitStatus: String,
  FiveArticleComponentArticleNoOneTopFabricFirstSubmitComment: String,
  FiveArticleComponentArticleNoOneTopFabricSecondSubmitDate: String,
  FiveArticleComponentArticleNoOneTopFabricSecondSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoOneTopFabricSecondSubmitStatus: String,
  FiveArticleComponentArticleNoOneTopFabricSecondSubmitComment: String,
  FiveArticleComponentArticleNoOneBottomFabricQuality: String,
  FiveArticleComponentArticleNoOneBottomFabricConstruction: String,
  FiveArticleComponentArticleNoOneBottomFabricWeight: String,
  FiveArticleComponentArticleNoOneBottomFabricColorComboName: String,
  FiveArticleComponentArticleNoOneBottomFabricType: String,
  FiveArticleComponentArticleNoOneBottomFabricStandard: String,
  FiveArticleComponentArticleNoOneBottomFabricSTDReceived: String,
  FiveArticleComponentArticleNoOneBottomFabricSTDReceivedDate: String,
  FiveArticleComponentArticleNoOneBottomFabricSTDDetail: String,
  FiveArticleComponentArticleNoOneBottomFabricSTDIfCADFile: String,
  FiveArticleComponentArticleNoOneBottomFabricFirstSubmitDate: String,
  FiveArticleComponentArticleNoOneBottomFabricFirstSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoOneBottomFabricFirstSubmitStatus: String,
  FiveArticleComponentArticleNoOneBottomFabricFirstSubmitComment: String,
  FiveArticleComponentArticleNoOneBottomFabricSecondSubmitDate: String,
  FiveArticleComponentArticleNoOneBottomFabricSecondSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoOneBottomFabricSecondSubmitStatus: String,
  FiveArticleComponentArticleNoOneBottomFabricSecondSubmitComment: String,
  FiveArticleComponentArticleNoTwoIdenticalTopBottomPieces: Boolean,
  FiveArticleComponentArticleNoTwoFabricQuality: String,
  FiveArticleComponentArticleNoTwoFabricConstruction: String,
  FiveArticleComponentArticleNoTwoWeight: String,
  FiveArticleComponentArticleNoTwoColorComboName: String,
  FiveArticleComponentArticleNoTwoType: String,
  FiveArticleComponentArticleNoTwoStandard: String,
  FiveArticleComponentArticleNoTwoSTDReceived: String,
  FiveArticleComponentArticleNoTwoSTDReceivedDate: String,
  FiveArticleComponentArticleNoTwoSTDDetail: String,
  FiveArticleComponentArticleNoTwoSTDIfCADFile: String,
  FiveArticleComponentArticleNoTwoFirstSubmitDate: String,
  FiveArticleComponentArticleNoTwoFirstSubmitCommentReceivedDate: String,
  FiveArticleComponentArticleNoTwoFirstSubmitStatus: String,
  FiveArticleComponentArticleNoTwoFirstSubmitComment: String,
  FiveArticleComponentArticleNoTwoSecondSubmitDate: String,
  FiveArticleComponentArticleNoTwoSecondSubmitCommentReceivedDate: String,
  FiveArticleComponentArticleNoTwoSecondSubmitStatus: String,
  FiveArticleComponentArticleNoTwoSecondSubmitComment: String,
  FiveArticleComponentArticleNoTwoTopFabricQuality: String,
  FiveArticleComponentArticleNoTwoTopFabricConstruction: String,
  FiveArticleComponentArticleNoTwoTopFabricWeight: String,
  FiveArticleComponentArticleNoTwoTopFabricColorComboName: String,
  FiveArticleComponentArticleNoTwoTopFabricType: String,
  FiveArticleComponentArticleNoTwoTopFabricStandard: String,
  FiveArticleComponentArticleNoTwoTopFabricSTDReceived: String,
  FiveArticleComponentArticleNoTwoTopFabricSTDReceivedDate: String,
  FiveArticleComponentArticleNoTwoTopFabricSTDDetail: String,
  FiveArticleComponentArticleNoTwoTopFabricSTDIfCADFile: String,
  FiveArticleComponentArticleNoTwoTopFabricFirstSubmitDate: String,
  FiveArticleComponentArticleNoTwoTopFabricFirstSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoTwoTopFabricFirstSubmitStatus: String,
  FiveArticleComponentArticleNoTwoTopFabricFirstSubmitComment: String,
  FiveArticleComponentArticleNoTwoTopFabricSecondSubmitDate: String,
  FiveArticleComponentArticleNoTwoTopFabricSecondSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoTwoTopFabricSecondSubmitStatus: String,
  FiveArticleComponentArticleNoTwoTopFabricSecondSubmitComment: String,
  FiveArticleComponentArticleNoTwoBottomFabricQuality: String,
  FiveArticleComponentArticleNoTwoBottomFabricConstruction: String,
  FiveArticleComponentArticleNoTwoBottomFabricWeight: String,
  FiveArticleComponentArticleNoTwoBottomFabricColorComboName: String,
  FiveArticleComponentArticleNoTwoBottomFabricType: String,
  FiveArticleComponentArticleNoTwoBottomFabricStandard: String,
  FiveArticleComponentArticleNoTwoBottomFabricSTDReceived: String,
  FiveArticleComponentArticleNoTwoBottomFabricSTDReceivedDate: String,
  FiveArticleComponentArticleNoTwoBottomFabricSTDDetail: String,
  FiveArticleComponentArticleNoTwoBottomFabricSTDIfCADFile: String,
  FiveArticleComponentArticleNoTwoBottomFabricFirstSubmitDate: String,
  FiveArticleComponentArticleNoTwoBottomFabricFirstSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoTwoBottomFabricFirstSubmitStatus: String,
  FiveArticleComponentArticleNoTwoBottomFabricFirstSubmitComment: String,
  FiveArticleComponentArticleNoTwoBottomFabricSecondSubmitDate: String,
  FiveArticleComponentArticleNoTwoBottomFabricSecondSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoTwoBottomFabricSecondSubmitStatus: String,
  FiveArticleComponentArticleNoTwoBottomFabricSecondSubmitComment: String,
  FiveArticleComponentArticleNoThreeIdenticalTopBottomPieces: Boolean,
  FiveArticleComponentArticleNoThreeFabricQuality: String,
  FiveArticleComponentArticleNoThreeFabricConstruction: String,
  FiveArticleComponentArticleNoThreeWeight: String,
  FiveArticleComponentArticleNoThreeColorComboName: String,
  FiveArticleComponentArticleNoThreeType: String,
  FiveArticleComponentArticleNoThreeStandard: String,
  FiveArticleComponentArticleNoThreeSTDReceived: String,
  FiveArticleComponentArticleNoThreeSTDReceivedDate: String,
  FiveArticleComponentArticleNoThreeSTDDetail: String,
  FiveArticleComponentArticleNoThreeSTDIfCADFile: String,
  FiveArticleComponentArticleNoThreeFirstSubmitDate: String,
  FiveArticleComponentArticleNoThreeFirstSubmitCommentReceivedDate: String,
  FiveArticleComponentArticleNoThreeFirstSubmitStatus: String,
  FiveArticleComponentArticleNoThreeFirstSubmitComment: String,
  FiveArticleComponentArticleNoThreeSecondSubmitDate: String,
  FiveArticleComponentArticleNoThreeSecondSubmitCommentReceivedDate: String,
  FiveArticleComponentArticleNoThreeSecondSubmitStatus: String,
  FiveArticleComponentArticleNoThreeSecondSubmitComment: String,
  FiveArticleComponentArticleNoThreeTopFabricQuality: String,
  FiveArticleComponentArticleNoThreeTopFabricConstruction: String,
  FiveArticleComponentArticleNoThreeTopFabricWeight: String,
  FiveArticleComponentArticleNoThreeTopFabricColorComboName: String,
  FiveArticleComponentArticleNoThreeTopFabricType: String,
  FiveArticleComponentArticleNoThreeTopFabricStandard: String,
  FiveArticleComponentArticleNoThreeTopFabricSTDReceived: String,
  FiveArticleComponentArticleNoThreeTopFabricSTDReceivedDate: String,
  FiveArticleComponentArticleNoThreeTopFabricSTDDetail: String,
  FiveArticleComponentArticleNoThreeTopFabricSTDIfCADFile: String,
  FiveArticleComponentArticleNoThreeTopFabricFirstSubmitDate: String,
  FiveArticleComponentArticleNoThreeTopFabricFirstSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoThreeTopFabricFirstSubmitStatus: String,
  FiveArticleComponentArticleNoThreeTopFabricFirstSubmitComment: String,
  FiveArticleComponentArticleNoThreeTopFabricSecondSubmitDate: String,
  FiveArticleComponentArticleNoThreeTopFabricSecondSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoThreeTopFabricSecondSubmitStatus: String,
  FiveArticleComponentArticleNoThreeTopFabricSecondSubmitComment: String,
  FiveArticleComponentArticleNoThreeBottomFabricQuality: String,
  FiveArticleComponentArticleNoThreeBottomFabricConstruction: String,
  FiveArticleComponentArticleNoThreeBottomFabricWeight: String,
  FiveArticleComponentArticleNoThreeBottomFabricColorComboName: String,
  FiveArticleComponentArticleNoThreeBottomFabricType: String,
  FiveArticleComponentArticleNoThreeBottomFabricStandard: String,
  FiveArticleComponentArticleNoThreeBottomFabricSTDReceived: String,
  FiveArticleComponentArticleNoThreeBottomFabricSTDReceivedDate: String,
  FiveArticleComponentArticleNoThreeBottomFabricSTDDetail: String,
  FiveArticleComponentArticleNoThreeBottomFabricSTDIfCADFile: String,
  FiveArticleComponentArticleNoThreeBottomFabricFirstSubmitDate: String,
  FiveArticleComponentArticleNoThreeBottomFabricFirstSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoThreeBottomFabricFirstSubmitStatus: String,
  FiveArticleComponentArticleNoThreeBottomFabricFirstSubmitComment: String,
  FiveArticleComponentArticleNoThreeBottomFabricSecondSubmitDate: String,
  FiveArticleComponentArticleNoThreeBottomFabricSecondSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoThreeBottomFabricSecondSubmitStatus: String,
  FiveArticleComponentArticleNoThreeBottomFabricSecondSubmitComment: String,
  FiveArticleComponentArticleNoFourIdenticalTopBottomPieces: Boolean,
  FiveArticleComponentArticleNoFourFabricQuality: String,
  FiveArticleComponentArticleNoFourFabricConstruction: String,
  FiveArticleComponentArticleNoFourWeight: String,
  FiveArticleComponentArticleNoFourColorComboName: String,
  FiveArticleComponentArticleNoFourType: String,
  FiveArticleComponentArticleNoFourStandard: String,
  FiveArticleComponentArticleNoFourSTDReceived: String,
  FiveArticleComponentArticleNoFourSTDReceivedDate: String,
  FiveArticleComponentArticleNoFourSTDDetail: String,
  FiveArticleComponentArticleNoFourSTDIfCADFile: String,
  FiveArticleComponentArticleNoFourFirstSubmitDate: String,
  FiveArticleComponentArticleNoFourFirstSubmitCommentReceivedDate: String,
  FiveArticleComponentArticleNoFourFirstSubmitStatus: String,
  FiveArticleComponentArticleNoFourFirstSubmitComment: String,
  FiveArticleComponentArticleNoFourSecondSubmitDate: String,
  FiveArticleComponentArticleNoFourSecondSubmitCommentReceivedDate: String,
  FiveArticleComponentArticleNoFourSecondSubmitStatus: String,
  FiveArticleComponentArticleNoFourSecondSubmitComment: String,
  FiveArticleComponentArticleNoFourTopFabricQuality: String,
  FiveArticleComponentArticleNoFourTopFabricConstruction: String,
  FiveArticleComponentArticleNoFourTopFabricWeight: String,
  FiveArticleComponentArticleNoFourTopFabricColorComboName: String,
  FiveArticleComponentArticleNoFourTopFabricType: String,
  FiveArticleComponentArticleNoFourTopFabricStandard: String,
  FiveArticleComponentArticleNoFourTopFabricSTDReceived: String,
  FiveArticleComponentArticleNoFourTopFabricSTDReceivedDate: String,
  FiveArticleComponentArticleNoFourTopFabricSTDDetail: String,
  FiveArticleComponentArticleNoFourTopFabricSTDIfCADFile: String,
  FiveArticleComponentArticleNoFourTopFabricFirstSubmitDate: String,
  FiveArticleComponentArticleNoFourTopFabricFirstSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoFourTopFabricFirstSubmitStatus: String,
  FiveArticleComponentArticleNoFourTopFabricFirstSubmitComment: String,
  FiveArticleComponentArticleNoFourTopFabricSecondSubmitDate: String,
  FiveArticleComponentArticleNoFourTopFabricSecondSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoFourTopFabricSecondSubmitStatus: String,
  FiveArticleComponentArticleNoFourTopFabricSecondSubmitComment: String,
  FiveArticleComponentArticleNoFourBottomFabricQuality: String,
  FiveArticleComponentArticleNoFourBottomFabricConstruction: String,
  FiveArticleComponentArticleNoFourBottomFabricWeight: String,
  FiveArticleComponentArticleNoFourBottomFabricColorComboName: String,
  FiveArticleComponentArticleNoFourBottomFabricType: String,
  FiveArticleComponentArticleNoFourBottomFabricStandard: String,
  FiveArticleComponentArticleNoFourBottomFabricSTDReceived: String,
  FiveArticleComponentArticleNoFourBottomFabricSTDReceivedDate: String,
  FiveArticleComponentArticleNoFourBottomFabricSTDDetail: String,
  FiveArticleComponentArticleNoFourBottomFabricSTDIfCADFile: String,
  FiveArticleComponentArticleNoFourBottomFabricFirstSubmitDate: String,
  FiveArticleComponentArticleNoFourBottomFabricFirstSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoFourBottomFabricFirstSubmitStatus: String,
  FiveArticleComponentArticleNoFourBottomFabricFirstSubmitComment: String,
  FiveArticleComponentArticleNoFourBottomFabricSecondSubmitDate: String,
  FiveArticleComponentArticleNoFourBottomFabricSecondSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoFourBottomFabricSecondSubmitStatus: String,
  FiveArticleComponentArticleNoFourBottomFabricSecondSubmitComment: String,
  FiveArticleComponentArticleNoFiveIdenticalTopBottomPieces: Boolean,
  FiveArticleComponentArticleNoFiveFabricQuality: String,
  FiveArticleComponentArticleNoFiveFabricConstruction: String,
  FiveArticleComponentArticleNoFiveWeight: String,
  FiveArticleComponentArticleNoFiveColorComboName: String,
  FiveArticleComponentArticleNoFiveType: String,
  FiveArticleComponentArticleNoFiveStandard: String,
  FiveArticleComponentArticleNoFiveSTDReceived: String,
  FiveArticleComponentArticleNoFiveSTDReceivedDate: String,
  FiveArticleComponentArticleNoFiveSTDDetail: String,
  FiveArticleComponentArticleNoFiveSTDIfCADFile: String,
  FiveArticleComponentArticleNoFiveFirstSubmitDate: String,
  FiveArticleComponentArticleNoFiveFirstSubmitCommentReceivedDate: String,
  FiveArticleComponentArticleNoFiveFirstSubmitStatus: String,
  FiveArticleComponentArticleNoFiveFirstSubmitComment: String,
  FiveArticleComponentArticleNoFiveSecondSubmitDate: String,
  FiveArticleComponentArticleNoFiveSecondSubmitCommentReceivedDate: String,
  FiveArticleComponentArticleNoFiveSecondSubmitStatus: String,
  FiveArticleComponentArticleNoFiveSecondSubmitComment: String,
  FiveArticleComponentArticleNoFiveTopFabricQuality: String,
  FiveArticleComponentArticleNoFiveTopFabricConstruction: String,
  FiveArticleComponentArticleNoFiveTopFabricWeight: String,
  FiveArticleComponentArticleNoFiveTopFabricColorComboName: String,
  FiveArticleComponentArticleNoFiveTopFabricType: String,
  FiveArticleComponentArticleNoFiveTopFabricStandard: String,
  FiveArticleComponentArticleNoFiveTopFabricSTDReceived: String,
  FiveArticleComponentArticleNoFiveTopFabricSTDReceivedDate: String,
  FiveArticleComponentArticleNoFiveTopFabricSTDDetail: String,
  FiveArticleComponentArticleNoFiveTopFabricSTDIfCADFile: String,
  FiveArticleComponentArticleNoFiveTopFabricFirstSubmitDate: String,
  FiveArticleComponentArticleNoFiveTopFabricFirstSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoFiveTopFabricFirstSubmitStatus: String,
  FiveArticleComponentArticleNoFiveTopFabricFirstSubmitComment: String,
  FiveArticleComponentArticleNoFiveTopFabricSecondSubmitDate: String,
  FiveArticleComponentArticleNoFiveTopFabricSecondSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoFiveTopFabricSecondSubmitStatus: String,
  FiveArticleComponentArticleNoFiveTopFabricSecondSubmitComment: String,
  FiveArticleComponentArticleNoFiveBottomFabricQuality: String,
  FiveArticleComponentArticleNoFiveBottomFabricConstruction: String,
  FiveArticleComponentArticleNoFiveBottomFabricWeight: String,
  FiveArticleComponentArticleNoFiveBottomFabricColorComboName: String,
  FiveArticleComponentArticleNoFiveBottomFabricType: String,
  FiveArticleComponentArticleNoFiveBottomFabricStandard: String,
  FiveArticleComponentArticleNoFiveBottomFabricSTDReceived: String,
  FiveArticleComponentArticleNoFiveBottomFabricSTDReceivedDate: String,
  FiveArticleComponentArticleNoFiveBottomFabricSTDDetail: String,
  FiveArticleComponentArticleNoFiveBottomFabricSTDIfCADFile: String,
  FiveArticleComponentArticleNoFiveBottomFabricFirstSubmitDate: String,
  FiveArticleComponentArticleNoFiveBottomFabricFirstSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoFiveBottomFabricFirstSubmitStatus: String,
  FiveArticleComponentArticleNoFiveBottomFabricFirstSubmitComment: String,
  FiveArticleComponentArticleNoFiveBottomFabricSecondSubmitDate: String,
  FiveArticleComponentArticleNoFiveBottomFabricSecondSubmitCommentReceivedDate:
    String,
  FiveArticleComponentArticleNoFiveBottomFabricSecondSubmitStatus: String,
  FiveArticleComponentArticleNoFiveBottomFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoOneIdenticalTopBottomPieces: Boolean,
  TenArticlesComponentArticleNoOneFabricQuality: String,
  TenArticlesComponentArticleNoOneFabricConstruction: String,
  TenArticlesComponentArticleNoOneWeight: String,
  TenArticlesComponentArticleNoOneColorComboName: String,
  TenArticlesComponentArticleNoOneType: String,
  TenArticlesComponentArticleNoOneStandard: String,
  TenArticlesComponentArticleNoOneSTDReceived: String,
  TenArticlesComponentArticleNoOneSTDReceivedDate: String,
  TenArticlesComponentArticleNoOneSTDDetail: String,
  TenArticlesComponentArticleNoOneSTDIfCADFile: String,
  TenArticlesComponentArticleNoOneFirstSubmitDate: String,
  TenArticlesComponentArticleNoOneFirstSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoOneFirstSubmitStatus: String,
  TenArticlesComponentArticleNoOneFirstSubmitComment: String,
  TenArticlesComponentArticleNoOneSecondSubmitDate: String,
  TenArticlesComponentArticleNoOneSecondSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoOneSecondSubmitStatus: String,
  TenArticlesComponentArticleNoOneSecondSubmitComment: String,
  TenArticlesComponentArticleNoOneTopFabricQuality: String,
  TenArticlesComponentArticleNoOneTopFabricConstruction: String,
  TenArticlesComponentArticleNoOneTopFabricWeight: String,
  TenArticlesComponentArticleNoOneTopFabricColorComboName: String,
  TenArticlesComponentArticleNoOneTopFabricType: String,
  TenArticlesComponentArticleNoOneTopFabricStandard: String,
  TenArticlesComponentArticleNoOneTopFabricSTDReceived: String,
  TenArticlesComponentArticleNoOneTopFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoOneTopFabricSTDDetail: String,
  TenArticlesComponentArticleNoOneTopFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoOneTopFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoOneTopFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoOneTopFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoOneTopFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoOneTopFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoOneTopFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoOneTopFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoOneTopFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoOneBottomFabricQuality: String,
  TenArticlesComponentArticleNoOneBottomFabricConstruction: String,
  TenArticlesComponentArticleNoOneBottomFabricWeight: String,
  TenArticlesComponentArticleNoOneBottomFabricColorComboName: String,
  TenArticlesComponentArticleNoOneBottomFabricType: String,
  TenArticlesComponentArticleNoOneBottomFabricStandard: String,
  TenArticlesComponentArticleNoOneBottomFabricSTDReceived: String,
  TenArticlesComponentArticleNoOneBottomFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoOneBottomFabricSTDDetail: String,
  TenArticlesComponentArticleNoOneBottomFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoOneBottomFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoOneBottomFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoOneBottomFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoOneBottomFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoOneBottomFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoOneBottomFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoOneBottomFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoOneBottomFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoTwoIdenticalTopBottomPieces: Boolean,
  TenArticlesComponentArticleNoTwoFabricQuality: String,
  TenArticlesComponentArticleNoTwoFabricConstruction: String,
  TenArticlesComponentArticleNoTwoWeight: String,
  TenArticlesComponentArticleNoTwoColorComboName: String,
  TenArticlesComponentArticleNoTwoType: String,
  TenArticlesComponentArticleNoTwoStandard: String,
  TenArticlesComponentArticleNoTwoSTDReceived: String,
  TenArticlesComponentArticleNoTwoSTDReceivedDate: String,
  TenArticlesComponentArticleNoTwoSTDDetail: String,
  TenArticlesComponentArticleNoTwoSTDIfCADFile: String,
  TenArticlesComponentArticleNoTwoFirstSubmitDate: String,
  TenArticlesComponentArticleNoTwoFirstSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoTwoFirstSubmitStatus: String,
  TenArticlesComponentArticleNoTwoFirstSubmitComment: String,
  TenArticlesComponentArticleNoTwoSecondSubmitDate: String,
  TenArticlesComponentArticleNoTwoSecondSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoTwoSecondSubmitStatus: String,
  TenArticlesComponentArticleNoTwoSecondSubmitComment: String,
  TenArticlesComponentArticleNoTwoTopFabricQuality: String,
  TenArticlesComponentArticleNoTwoTopFabricConstruction: String,
  TenArticlesComponentArticleNoTwoTopFabricWeight: String,
  TenArticlesComponentArticleNoTwoTopFabricColorComboName: String,
  TenArticlesComponentArticleNoTwoTopFabricType: String,
  TenArticlesComponentArticleNoTwoTopFabricStandard: String,
  TenArticlesComponentArticleNoTwoTopFabricSTDReceived: String,
  TenArticlesComponentArticleNoTwoTopFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoTwoTopFabricSTDDetail: String,
  TenArticlesComponentArticleNoTwoTopFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoTwoTopFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoTwoTopFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoTwoTopFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoTwoTopFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoTwoTopFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoTwoTopFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoTwoTopFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoTwoTopFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoTwoBottomFabricQuality: String,
  TenArticlesComponentArticleNoTwoBottomFabricConstruction: String,
  TenArticlesComponentArticleNoTwoBottomFabricWeight: String,
  TenArticlesComponentArticleNoTwoBottomFabricColorComboName: String,
  TenArticlesComponentArticleNoTwoBottomFabricType: String,
  TenArticlesComponentArticleNoTwoBottomFabricStandard: String,
  TenArticlesComponentArticleNoTwoBottomFabricSTDReceived: String,
  TenArticlesComponentArticleNoTwoBottomFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoTwoBottomFabricSTDDetail: String,
  TenArticlesComponentArticleNoTwoBottomFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoTwoBottomFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoTwoBottomFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoTwoBottomFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoTwoBottomFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoTwoBottomFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoTwoBottomFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoTwoBottomFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoTwoBottomFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoThreeIdenticalTopBottomPieces: Boolean,
  TenArticlesComponentArticleNoThreeFabricQuality: String,
  TenArticlesComponentArticleNoThreeFabricConstruction: String,
  TenArticlesComponentArticleNoThreeWeight: String,
  TenArticlesComponentArticleNoThreeColorComboName: String,
  TenArticlesComponentArticleNoThreeType: String,
  TenArticlesComponentArticleNoThreeStandard: String,
  TenArticlesComponentArticleNoThreeSTDReceived: String,
  TenArticlesComponentArticleNoThreeSTDReceivedDate: String,
  TenArticlesComponentArticleNoThreeSTDDetail: String,
  TenArticlesComponentArticleNoThreeSTDIfCADFile: String,
  TenArticlesComponentArticleNoThreeFirstSubmitDate: String,
  TenArticlesComponentArticleNoThreeFirstSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoThreeFirstSubmitStatus: String,
  TenArticlesComponentArticleNoThreeFirstSubmitComment: String,
  TenArticlesComponentArticleNoThreeSecondSubmitDate: String,
  TenArticlesComponentArticleNoThreeSecondSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoThreeSecondSubmitStatus: String,
  TenArticlesComponentArticleNoThreeSecondSubmitComment: String,
  TenArticlesComponentArticleNoThreeTopFabricQuality: String,
  TenArticlesComponentArticleNoThreeTopFabricConstruction: String,
  TenArticlesComponentArticleNoThreeTopFabricWeight: String,
  TenArticlesComponentArticleNoThreeTopFabricColorComboName: String,
  TenArticlesComponentArticleNoThreeTopFabricType: String,
  TenArticlesComponentArticleNoThreeTopFabricStandard: String,
  TenArticlesComponentArticleNoThreeTopFabricSTDReceived: String,
  TenArticlesComponentArticleNoThreeTopFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoThreeTopFabricSTDDetail: String,
  TenArticlesComponentArticleNoThreeTopFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoThreeTopFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoThreeTopFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoThreeTopFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoThreeTopFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoThreeTopFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoThreeTopFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoThreeTopFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoThreeTopFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoThreeBottomFabricQuality: String,
  TenArticlesComponentArticleNoThreeBottomFabricConstruction: String,
  TenArticlesComponentArticleNoThreeBottomFabricWeight: String,
  TenArticlesComponentArticleNoThreeBottomFabricColorComboName: String,
  TenArticlesComponentArticleNoThreeBottomFabricType: String,
  TenArticlesComponentArticleNoThreeBottomFabricStandard: String,
  TenArticlesComponentArticleNoThreeBottomFabricSTDReceived: String,
  TenArticlesComponentArticleNoThreeBottomFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoThreeBottomFabricSTDDetail: String,
  TenArticlesComponentArticleNoThreeBottomFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoThreeBottomFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoThreeBottomFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoThreeBottomFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoThreeBottomFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoThreeBottomFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoThreeBottomFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoThreeBottomFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoThreeBottomFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoFourIdenticalTopBottomPieces: Boolean,
  TenArticlesComponentArticleNoFourFabricQuality: String,
  TenArticlesComponentArticleNoFourFabricConstruction: String,
  TenArticlesComponentArticleNoFourWeight: String,
  TenArticlesComponentArticleNoFourColorComboName: String,
  TenArticlesComponentArticleNoFourType: String,
  TenArticlesComponentArticleNoFourStandard: String,
  TenArticlesComponentArticleNoFourSTDReceived: String,
  TenArticlesComponentArticleNoFourSTDReceivedDate: String,
  TenArticlesComponentArticleNoFourSTDDetail: String,
  TenArticlesComponentArticleNoFourSTDIfCADFile: String,
  TenArticlesComponentArticleNoFourFirstSubmitDate: String,
  TenArticlesComponentArticleNoFourFirstSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoFourFirstSubmitStatus: String,
  TenArticlesComponentArticleNoFourFirstSubmitComment: String,
  TenArticlesComponentArticleNoFourSecondSubmitDate: String,
  TenArticlesComponentArticleNoFourSecondSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoFourSecondSubmitStatus: String,
  TenArticlesComponentArticleNoFourSecondSubmitComment: String,
  TenArticlesComponentArticleNoFourTopFabricQuality: String,
  TenArticlesComponentArticleNoFourTopFabricConstruction: String,
  TenArticlesComponentArticleNoFourTopFabricWeight: String,
  TenArticlesComponentArticleNoFourTopFabricColorComboName: String,
  TenArticlesComponentArticleNoFourTopFabricType: String,
  TenArticlesComponentArticleNoFourTopFabricStandard: String,
  TenArticlesComponentArticleNoFourTopFabricSTDReceived: String,
  TenArticlesComponentArticleNoFourTopFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoFourTopFabricSTDDetail: String,
  TenArticlesComponentArticleNoFourTopFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoFourTopFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoFourTopFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoFourTopFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoFourTopFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoFourTopFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoFourTopFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoFourTopFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoFourTopFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoFourBottomFabricQuality: String,
  TenArticlesComponentArticleNoFourBottomFabricConstruction: String,
  TenArticlesComponentArticleNoFourBottomFabricWeight: String,
  TenArticlesComponentArticleNoFourBottomFabricColorComboName: String,
  TenArticlesComponentArticleNoFourBottomFabricType: String,
  TenArticlesComponentArticleNoFourBottomFabricStandard: String,
  TenArticlesComponentArticleNoFourBottomFabricSTDReceived: String,
  TenArticlesComponentArticleNoFourBottomFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoFourBottomFabricSTDDetail: String,
  TenArticlesComponentArticleNoFourBottomFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoFourBottomFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoFourBottomFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoFourBottomFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoFourBottomFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoFourBottomFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoFourBottomFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoFourBottomFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoFourBottomFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoFiveIdenticalTopBottomPieces: Boolean,
  TenArticlesComponentArticleNoFiveFabricQuality: String,
  TenArticlesComponentArticleNoFiveFabricConstruction: String,
  TenArticlesComponentArticleNoFiveWeight: String,
  TenArticlesComponentArticleNoFiveColorComboName: String,
  TenArticlesComponentArticleNoFiveType: String,
  TenArticlesComponentArticleNoFiveStandard: String,
  TenArticlesComponentArticleNoFiveSTDReceived: String,
  TenArticlesComponentArticleNoFiveSTDReceivedDate: String,
  TenArticlesComponentArticleNoFiveSTDDetail: String,
  TenArticlesComponentArticleNoFiveSTDIfCADFile: String,
  TenArticlesComponentArticleNoFiveFirstSubmitDate: String,
  TenArticlesComponentArticleNoFiveFirstSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoFiveFirstSubmitStatus: String,
  TenArticlesComponentArticleNoFiveFirstSubmitComment: String,
  TenArticlesComponentArticleNoFiveSecondSubmitDate: String,
  TenArticlesComponentArticleNoFiveSecondSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoFiveSecondSubmitStatus: String,
  TenArticlesComponentArticleNoFiveSecondSubmitComment: String,
  TenArticlesComponentArticleNoFiveTopFabricQuality: String,
  TenArticlesComponentArticleNoFiveTopFabricConstruction: String,
  TenArticlesComponentArticleNoFiveTopFabricWeight: String,
  TenArticlesComponentArticleNoFiveTopFabricColorComboName: String,
  TenArticlesComponentArticleNoFiveTopFabricType: String,
  TenArticlesComponentArticleNoFiveTopFabricStandard: String,
  TenArticlesComponentArticleNoFiveTopFabricSTDReceived: String,
  TenArticlesComponentArticleNoFiveTopFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoFiveTopFabricSTDDetail: String,
  TenArticlesComponentArticleNoFiveTopFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoFiveTopFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoFiveTopFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoFiveTopFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoFiveTopFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoFiveTopFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoFiveTopFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoFiveTopFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoFiveTopFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoFiveBottomFabricQuality: String,
  TenArticlesComponentArticleNoFiveBottomFabricConstruction: String,
  TenArticlesComponentArticleNoFiveBottomFabricWeight: String,
  TenArticlesComponentArticleNoFiveBottomFabricColorComboName: String,
  TenArticlesComponentArticleNoFiveBottomFabricType: String,
  TenArticlesComponentArticleNoFiveBottomFabricStandard: String,
  TenArticlesComponentArticleNoFiveBottomFabricSTDReceived: String,
  TenArticlesComponentArticleNoFiveBottomFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoFiveBottomFabricSTDDetail: String,
  TenArticlesComponentArticleNoFiveBottomFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoFiveBottomFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoFiveBottomFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoFiveBottomFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoFiveBottomFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoFiveBottomFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoFiveBottomFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoFiveBottomFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoFiveBottomFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoSixIdenticalTopBottomPieces: Boolean,
  TenArticlesComponentArticleNoSixFabricQuality: String,
  TenArticlesComponentArticleNoSixFabricConstruction: String,
  TenArticlesComponentArticleNoSixWeight: String,
  TenArticlesComponentArticleNoSixColorComboName: String,
  TenArticlesComponentArticleNoSixType: String,
  TenArticlesComponentArticleNoSixStandard: String,
  TenArticlesComponentArticleNoSixSTDReceived: String,
  TenArticlesComponentArticleNoSixSTDReceivedDate: String,
  TenArticlesComponentArticleNoSixSTDDetail: String,
  TenArticlesComponentArticleNoSixSTDIfCADFile: String,
  TenArticlesComponentArticleNoSixFirstSubmitDate: String,
  TenArticlesComponentArticleNoSixFirstSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoSixFirstSubmitStatus: String,
  TenArticlesComponentArticleNoSixFirstSubmitComment: String,
  TenArticlesComponentArticleNoSixSecondSubmitDate: String,
  TenArticlesComponentArticleNoSixSecondSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoSixSecondSubmitStatus: String,
  TenArticlesComponentArticleNoSixSecondSubmitComment: String,
  TenArticlesComponentArticleNoSixTopFabricQuality: String,
  TenArticlesComponentArticleNoSixTopFabricConstruction: String,
  TenArticlesComponentArticleNoSixTopFabricWeight: String,
  TenArticlesComponentArticleNoSixTopFabricColorComboName: String,
  TenArticlesComponentArticleNoSixTopFabricType: String,
  TenArticlesComponentArticleNoSixTopFabricStandard: String,
  TenArticlesComponentArticleNoSixTopFabricSTDReceived: String,
  TenArticlesComponentArticleNoSixTopFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoSixTopFabricSTDDetail: String,
  TenArticlesComponentArticleNoSixTopFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoSixTopFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoSixTopFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoSixTopFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoSixTopFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoSixTopFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoSixTopFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoSixTopFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoSixTopFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoSixBottomFabricQuality: String,
  TenArticlesComponentArticleNoSixBottomFabricConstruction: String,
  TenArticlesComponentArticleNoSixBottomFabricWeight: String,
  TenArticlesComponentArticleNoSixBottomFabricColorComboName: String,
  TenArticlesComponentArticleNoSixBottomFabricType: String,
  TenArticlesComponentArticleNoSixBottomFabricStandard: String,
  TenArticlesComponentArticleNoSixBottomFabricSTDReceived: String,
  TenArticlesComponentArticleNoSixBottomFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoSixBottomFabricSTDDetail: String,
  TenArticlesComponentArticleNoSixBottomFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoSixBottomFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoSixBottomFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoSixBottomFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoSixBottomFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoSixBottomFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoSixBottomFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoSixBottomFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoSixBottomFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoSevenIdenticalTopBottomPieces: Boolean,
  TenArticlesComponentArticleNoSevenFabricQuality: String,
  TenArticlesComponentArticleNoSevenFabricConstruction: String,
  TenArticlesComponentArticleNoSevenWeight: String,
  TenArticlesComponentArticleNoSevenColorComboName: String,
  TenArticlesComponentArticleNoSevenType: String,
  TenArticlesComponentArticleNoSevenStandard: String,
  TenArticlesComponentArticleNoSevenSTDReceived: String,
  TenArticlesComponentArticleNoSevenSTDReceivedDate: String,
  TenArticlesComponentArticleNoSevenSTDDetail: String,
  TenArticlesComponentArticleNoSevenSTDIfCADFile: String,
  TenArticlesComponentArticleNoSevenFirstSubmitDate: String,
  TenArticlesComponentArticleNoSevenFirstSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoSevenFirstSubmitStatus: String,
  TenArticlesComponentArticleNoSevenFirstSubmitComment: String,
  TenArticlesComponentArticleNoSevenSecondSubmitDate: String,
  TenArticlesComponentArticleNoSevenSecondSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoSevenSecondSubmitStatus: String,
  TenArticlesComponentArticleNoSevenSecondSubmitComment: String,
  TenArticlesComponentArticleNoSevenTopFabricQuality: String,
  TenArticlesComponentArticleNoSevenTopFabricConstruction: String,
  TenArticlesComponentArticleNoSevenTopFabricWeight: String,
  TenArticlesComponentArticleNoSevenTopFabricColorComboName: String,
  TenArticlesComponentArticleNoSevenTopFabricType: String,
  TenArticlesComponentArticleNoSevenTopFabricStandard: String,
  TenArticlesComponentArticleNoSevenTopFabricSTDReceived: String,
  TenArticlesComponentArticleNoSevenTopFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoSevenTopFabricSTDDetail: String,
  TenArticlesComponentArticleNoSevenTopFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoSevenTopFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoSevenTopFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoSevenTopFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoSevenTopFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoSevenTopFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoSevenTopFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoSevenTopFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoSevenTopFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoSevenBottomFabricQuality: String,
  TenArticlesComponentArticleNoSevenBottomFabricConstruction: String,
  TenArticlesComponentArticleNoSevenBottomFabricWeight: String,
  TenArticlesComponentArticleNoSevenBottomFabricColorComboName: String,
  TenArticlesComponentArticleNoSevenBottomFabricType: String,
  TenArticlesComponentArticleNoSevenBottomFabricStandard: String,
  TenArticlesComponentArticleNoSevenBottomFabricSTDReceived: String,
  TenArticlesComponentArticleNoSevenBottomFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoSevenBottomFabricSTDDetail: String,
  TenArticlesComponentArticleNoSevenBottomFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoSevenBottomFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoSevenBottomFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoSevenBottomFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoSevenBottomFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoSevenBottomFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoSevenBottomFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoSevenBottomFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoSevenBottomFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoEightIdenticalTopBottomPieces: Boolean,
  TenArticlesComponentArticleNoEightFabricQuality: String,
  TenArticlesComponentArticleNoEightFabricConstruction: String,
  TenArticlesComponentArticleNoEightWeight: String,
  TenArticlesComponentArticleNoEightColorComboName: String,
  TenArticlesComponentArticleNoEightType: String,
  TenArticlesComponentArticleNoEightStandard: String,
  TenArticlesComponentArticleNoEightSTDReceived: String,
  TenArticlesComponentArticleNoEightSTDReceivedDate: String,
  TenArticlesComponentArticleNoEightSTDDetail: String,
  TenArticlesComponentArticleNoEightSTDIfCADFile: String,
  TenArticlesComponentArticleNoEightFirstSubmitDate: String,
  TenArticlesComponentArticleNoEightFirstSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoEightFirstSubmitStatus: String,
  TenArticlesComponentArticleNoEightFirstSubmitComment: String,
  TenArticlesComponentArticleNoEightSecondSubmitDate: String,
  TenArticlesComponentArticleNoEightSecondSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoEightSecondSubmitStatus: String,
  TenArticlesComponentArticleNoEightSecondSubmitComment: String,
  TenArticlesComponentArticleNoEightTopFabricQuality: String,
  TenArticlesComponentArticleNoEightTopFabricConstruction: String,
  TenArticlesComponentArticleNoEightTopFabricWeight: String,
  TenArticlesComponentArticleNoEightTopFabricColorComboName: String,
  TenArticlesComponentArticleNoEightTopFabricType: String,
  TenArticlesComponentArticleNoEightTopFabricStandard: String,
  TenArticlesComponentArticleNoEightTopFabricSTDReceived: String,
  TenArticlesComponentArticleNoEightTopFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoEightTopFabricSTDDetail: String,
  TenArticlesComponentArticleNoEightTopFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoEightTopFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoEightTopFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoEightTopFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoEightTopFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoEightTopFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoEightTopFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoEightTopFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoEightTopFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoEightBottomFabricQuality: String,
  TenArticlesComponentArticleNoEightBottomFabricConstruction: String,
  TenArticlesComponentArticleNoEightBottomFabricWeight: String,
  TenArticlesComponentArticleNoEightBottomFabricColorComboName: String,
  TenArticlesComponentArticleNoEightBottomFabricType: String,
  TenArticlesComponentArticleNoEightBottomFabricStandard: String,
  TenArticlesComponentArticleNoEightBottomFabricSTDReceived: String,
  TenArticlesComponentArticleNoEightBottomFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoEightBottomFabricSTDDetail: String,
  TenArticlesComponentArticleNoEightBottomFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoEightBottomFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoEightBottomFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoEightBottomFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoEightBottomFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoEightBottomFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoEightBottomFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoEightBottomFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoEightBottomFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoNineIdenticalTopBottomPieces: Boolean,
  TenArticlesComponentArticleNoNineFabricQuality: String,
  TenArticlesComponentArticleNoNineFabricConstruction: String,
  TenArticlesComponentArticleNoNineWeight: String,
  TenArticlesComponentArticleNoNineColorComboName: String,
  TenArticlesComponentArticleNoNineType: String,
  TenArticlesComponentArticleNoNineStandard: String,
  TenArticlesComponentArticleNoNineSTDReceived: String,
  TenArticlesComponentArticleNoNineSTDReceivedDate: String,
  TenArticlesComponentArticleNoNineSTDDetail: String,
  TenArticlesComponentArticleNoNineSTDIfCADFile: String,
  TenArticlesComponentArticleNoNineFirstSubmitDate: String,
  TenArticlesComponentArticleNoNineFirstSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoNineFirstSubmitStatus: String,
  TenArticlesComponentArticleNoNineFirstSubmitComment: String,
  TenArticlesComponentArticleNoNineSecondSubmitDate: String,
  TenArticlesComponentArticleNoNineSecondSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoNineSecondSubmitStatus: String,
  TenArticlesComponentArticleNoNineSecondSubmitComment: String,
  TenArticlesComponentArticleNoNineTopFabricQuality: String,
  TenArticlesComponentArticleNoNineTopFabricConstruction: String,
  TenArticlesComponentArticleNoNineTopFabricWeight: String,
  TenArticlesComponentArticleNoNineTopFabricColorComboName: String,
  TenArticlesComponentArticleNoNineTopFabricType: String,
  TenArticlesComponentArticleNoNineTopFabricStandard: String,
  TenArticlesComponentArticleNoNineTopFabricSTDReceived: String,
  TenArticlesComponentArticleNoNineTopFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoNineTopFabricSTDDetail: String,
  TenArticlesComponentArticleNoNineTopFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoNineTopFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoNineTopFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoNineTopFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoNineTopFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoNineTopFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoNineTopFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoNineTopFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoNineTopFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoNineBottomFabricQuality: String,
  TenArticlesComponentArticleNoNineBottomFabricConstruction: String,
  TenArticlesComponentArticleNoNineBottomFabricWeight: String,
  TenArticlesComponentArticleNoNineBottomFabricColorComboName: String,
  TenArticlesComponentArticleNoNineBottomFabricType: String,
  TenArticlesComponentArticleNoNineBottomFabricStandard: String,
  TenArticlesComponentArticleNoNineBottomFabricSTDReceived: String,
  TenArticlesComponentArticleNoNineBottomFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoNineBottomFabricSTDDetail: String,
  TenArticlesComponentArticleNoNineBottomFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoNineBottomFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoNineBottomFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoNineBottomFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoNineBottomFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoNineBottomFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoNineBottomFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoNineBottomFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoNineBottomFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoTenIdenticalTopBottomPieces: Boolean,
  TenArticlesComponentArticleNoTenFabricQuality: String,
  TenArticlesComponentArticleNoTenFabricConstruction: String,
  TenArticlesComponentArticleNoTenWeight: String,
  TenArticlesComponentArticleNoTenColorComboName: String,
  TenArticlesComponentArticleNoTenType: String,
  TenArticlesComponentArticleNoTenStandard: String,
  TenArticlesComponentArticleNoTenSTDReceived: String,
  TenArticlesComponentArticleNoTenSTDReceivedDate: String,
  TenArticlesComponentArticleNoTenSTDDetail: String,
  TenArticlesComponentArticleNoTenSTDIfCADFile: String,
  TenArticlesComponentArticleNoTenFirstSubmitDate: String,
  TenArticlesComponentArticleNoTenFirstSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoTenFirstSubmitStatus: String,
  TenArticlesComponentArticleNoTenFirstSubmitComment: String,
  TenArticlesComponentArticleNoTenSecondSubmitDate: String,
  TenArticlesComponentArticleNoTenSecondSubmitCommentReceivedDate: String,
  TenArticlesComponentArticleNoTenSecondSubmitStatus: String,
  TenArticlesComponentArticleNoTenSecondSubmitComment: String,
  TenArticlesComponentArticleNoTenTopFabricQuality: String,
  TenArticlesComponentArticleNoTenTopFabricConstruction: String,
  TenArticlesComponentArticleNoTenTopFabricWeight: String,
  TenArticlesComponentArticleNoTenTopFabricColorComboName: String,
  TenArticlesComponentArticleNoTenTopFabricType: String,
  TenArticlesComponentArticleNoTenTopFabricStandard: String,
  TenArticlesComponentArticleNoTenTopFabricSTDReceived: String,
  TenArticlesComponentArticleNoTenTopFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoTenTopFabricSTDDetail: String,
  TenArticlesComponentArticleNoTenTopFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoTenTopFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoTenTopFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoTenTopFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoTenTopFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoTenTopFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoTenTopFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoTenTopFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoTenTopFabricSecondSubmitComment: String,
  TenArticlesComponentArticleNoTenBottomFabricQuality: String,
  TenArticlesComponentArticleNoTenBottomFabricConstruction: String,
  TenArticlesComponentArticleNoTenBottomFabricWeight: String,
  TenArticlesComponentArticleNoTenBottomFabricColorComboName: String,
  TenArticlesComponentArticleNoTenBottomFabricType: String,
  TenArticlesComponentArticleNoTenBottomFabricStandard: String,
  TenArticlesComponentArticleNoTenBottomFabricSTDReceived: String,
  TenArticlesComponentArticleNoTenBottomFabricSTDReceivedDate: String,
  TenArticlesComponentArticleNoTenBottomFabricSTDDetail: String,
  TenArticlesComponentArticleNoTenBottomFabricSTDIfCADFile: String,
  TenArticlesComponentArticleNoTenBottomFabricFirstSubmitDate: String,
  TenArticlesComponentArticleNoTenBottomFabricFirstSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoTenBottomFabricFirstSubmitStatus: String,
  TenArticlesComponentArticleNoTenBottomFabricFirstSubmitComment: String,
  TenArticlesComponentArticleNoTenBottomFabricSecondSubmitDate: String,
  TenArticlesComponentArticleNoTenBottomFabricSecondSubmitCommentReceivedDate:
    String,
  TenArticlesComponentArticleNoTenBottomFabricSecondSubmitStatus: String,
  TenArticlesComponentArticleNoTenBottomFabricSecondSubmitComment: String,
});

const ARTICLES = mongoose.model("articles", articlesSchema);
module.exports = ARTICLES;
